# All necesary modules 
import os
import subprocess
import pandas as pd
import glob
import sys

# This script will create an abundance.tsv for each SRR which will contain 
# all of the abundances for each gene. 
# This Script will also create a SRRXXXX_final.csv for each SRR which will match each 
# target_id from the abundance.tsv to its WormBase ID for phase 2-4. 
# Note: in order to use this script you will first need to download the necessary files 
# from https://parasite.wormbase.org/Caenorhabditis_elegans_prjna13758/Info/Index/ 
# to run this script. 
# This git hub contains a transcript_map.csv and celegans_index.idx that analyses the files found on that 
# website and filters the useful data so that the user does not have to download them. 
# Instructions on how to run the script can be found in the README of GitHub. 
#____________________________________________________________________________

# Get the absolute path of the directory where this script is located
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Go up one level to the project root
BASE_DIR = os.path.dirname(SCRIPT_DIR)

# Point this to where the FASTQs and FASTA are currently located
DATA_DIR = os.path.join(BASE_DIR, "Data", "sample_test_data")
OUTPUT_DIR = os.path.join(BASE_DIR, "Results", "kallisto_outputs")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Set up all of the file paths 
# TRANSCRIPTOME_FA is only needed to build the index, because the index is included in this GitHub, it won't be needed to test the sample data.
TRANSCRIPTOME_FA = os.path.join(DATA_DIR, "caenorhabditis_elegans.PRJNA13758.WBPS19.mRNA_transcripts.fa")
INDEX_FILE = os.path.join(BASE_DIR, "celegans_index.idx")
MAPPING_FILE = os.path.join(BASE_DIR, "Data", "transcript_map.csv")

# Make sure that the index is built 
# If the index is not built, then tell then tell user with a print statement.
# Only build this if it doesn't already exist to save time.  
if not os.path.exists(INDEX_FILE):
    if os.path.exists(TRANSCRIPTOME_FA):
        print(f"Building index...")
        subprocess.run(["kallisto", "index", "-i", INDEX_FILE, TRANSCRIPTOME_FA], check=True)
    else:
        sys.exit(f"ERROR: Index and FASTA missing.")


# Using DATA_DIR because that is where we defined the path earlier
# Identify all paired-end FASTQ files in the data directory.
fastq_files = sorted(glob.glob(os.path.join(DATA_DIR, "*.fastq")))
samples = {}
# Group R1 and R2 files into pairs by their SRR sample ID.
for fq in fastq_files:
    name = os.path.basename(fq)
    if "_1.fastq" in name:
        base = name.replace("_1.fastq", "")
        # Again, using DATA_DIR here
        mate = os.path.join(DATA_DIR, base + "_2.fastq")
        if os.path.exists(mate):
            samples[base] = (fq, mate)
# Run the 'kallisto quant' command for each pair found.
for sample, (fq1, fq2) in samples.items():
    out_dir = os.path.join(OUTPUT_DIR, sample)
    if not os.path.exists(out_dir):
        print(f"Processing {sample}...")
        os.makedirs(out_dir, exist_ok=True)
        # -b 100 sets 100 bootstrap samples for statistical robustness.
        subprocess.run(["kallisto", "quant", "-i", INDEX_FILE, "-o", out_dir, "-b", "100", fq1, fq2], check=True)


# Using MAPPING_FILE as defined in Section 2
# Let the user know if the file is not found 
# Raw Kallisto output uses transcript IDs that need to be assigned Gene IDs (WBGene)
if not os.path.exists(MAPPING_FILE):
    sys.exit(f"ERROR: {MAPPING_FILE} not found. Ensure it is in Data/transcript_map.csv")

print(f"Loading transcript-to-gene map from {os.path.basename(MAPPING_FILE)}...")
map_df = pd.read_csv(MAPPING_FILE)

for sample in samples.keys():
    abundance_path = os.path.join(OUTPUT_DIR, sample, "abundance.tsv")
    if os.path.exists(abundance_path):
        # Load the raw TSV generated by Kallisto
        df = pd.read_csv(abundance_path, sep='\t')
        
        # Clean the data
        # Strips "transcript:" or "mRNA:" prefixes if the GFF3 had them.
        # This ensures IDs like 'transcript:B0213.1' match 'B0213.1' in our map.
        df['target_id'] = df['target_id'].astype(str).str.split(":").str[-1]
        
        # Attach the WBGene_ID column from the map to the Kallisto data.
        final_df = df.merge(map_df, on="target_id", how="left")
        # Create a final dataframe containing WBGene_ID, target_ID, and tpm 
        output_file = os.path.join(OUTPUT_DIR, sample, f"{sample}_final.csv")
        final_df[['target_id', 'WBGene_ID', 'tpm']].to_csv(output_file, index=False)
        print(f"Sample {sample}: Final CSV created.")

print("\nPhase 1 execution finished.")
